site_name: Wetter Arbon

pages:
    - Home: index.md
    - Meetings:
        - idee.md
        - kickoff.md
        - meetings.md
    - Reports BA:
        - KW08 : KW08.md
        - KW09 : KW09.md
        - KW10 : KW10.md
        - KW11 : KW11.md
        - KW12 : KW12.md
        - KW13 : KW13.md
        - KW14 : KW14.md
        - KW15 : KW15.md
        - KW16 : KW16.md
        - KW17 : KW17.md
        - KW18 : KW18.md
        - KW19 : KW19.md
        - KW20 : KW20.md
        - KW21 : KW21.md
        - KW22 : KW22.md
        - KW23 : KW23.md
        - KW24 : KW24.md
        - KW25 : KW25.md
        - KW26 : KW26.md
        - KW27 : KW27.md
    - Reports FM:
        - KW44 : KW44.md
        - KW45 : KW45.md
        - KW46 : KW46.md
        - KW47 : KW47.md
        - KW48 : KW48.md
        - KW49 : KW49.md
        - KW50 : KW50.md
        - KW51 : KW51.md
    - About: about.md
# theme: readthedocs
